// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NumOfCustomer.proto

package Generated_NumberOfCustomer_Service;

public final class CA1 {
  private CA1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CurrentCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CurrentCustomer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023NumOfCustomer.proto\022\010service3\"\034\n\010Locat" +
      "ion\022\020\n\010location\030\001 \001(\t\"7\n\017CurrentCustomer" +
      "\022\020\n\010location\030\001 \001(\t\022\022\n\ncurrentNum\030\002 \001(\0052]" +
      "\n\020NumberOfCustomer\022I\n\022CheckNumOfCustomer" +
      "\022\022.service3.Location\032\031.service3.CurrentC" +
      "ustomer\"\000(\0010\001B+\n\"Generated_NumberOfCusto" +
      "mer_ServiceB\003CA1P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_Location_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_service3_CurrentCustomer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_CurrentCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CurrentCustomer_descriptor,
        new java.lang.String[] { "Location", "CurrentNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
