// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NumOfCustomer.proto

package Generated_NumberOfCustomer_Service;

public interface CurrentCustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.CurrentCustomer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int32 currentNum = 2;</code>
   */
  int getCurrentNum();
}
