// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMgmt.proto

package Stock_Management_Service;

/**
 * Protobuf type {@code service1.TotalPrice}
 */
public  final class TotalPrice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.TotalPrice)
    TotalPriceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TotalPrice.newBuilder() to construct.
  private TotalPrice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TotalPrice() {
    quantityOfItems_ = 0;
    totalPrice_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TotalPrice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            quantityOfItems_ = input.readInt32();
            break;
          }
          case 17: {

            totalPrice_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Stock_Management_Service.CA1.internal_static_service1_TotalPrice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Stock_Management_Service.CA1.internal_static_service1_TotalPrice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Stock_Management_Service.TotalPrice.class, Stock_Management_Service.TotalPrice.Builder.class);
  }

  public static final int QUANTITY_OF_ITEMS_FIELD_NUMBER = 1;
  private int quantityOfItems_;
  /**
   * <code>int32 quantity_of_items = 1;</code>
   */
  public int getQuantityOfItems() {
    return quantityOfItems_;
  }

  public static final int TOTALPRICE_FIELD_NUMBER = 2;
  private double totalPrice_;
  /**
   * <code>double totalPrice = 2;</code>
   */
  public double getTotalPrice() {
    return totalPrice_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (quantityOfItems_ != 0) {
      output.writeInt32(1, quantityOfItems_);
    }
    if (totalPrice_ != 0D) {
      output.writeDouble(2, totalPrice_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (quantityOfItems_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, quantityOfItems_);
    }
    if (totalPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, totalPrice_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Stock_Management_Service.TotalPrice)) {
      return super.equals(obj);
    }
    Stock_Management_Service.TotalPrice other = (Stock_Management_Service.TotalPrice) obj;

    boolean result = true;
    result = result && (getQuantityOfItems()
        == other.getQuantityOfItems());
    result = result && (
        java.lang.Double.doubleToLongBits(getTotalPrice())
        == java.lang.Double.doubleToLongBits(
            other.getTotalPrice()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUANTITY_OF_ITEMS_FIELD_NUMBER;
    hash = (53 * hash) + getQuantityOfItems();
    hash = (37 * hash) + TOTALPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTotalPrice()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Stock_Management_Service.TotalPrice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Stock_Management_Service.TotalPrice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Stock_Management_Service.TotalPrice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Stock_Management_Service.TotalPrice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Stock_Management_Service.TotalPrice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service1.TotalPrice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.TotalPrice)
      Stock_Management_Service.TotalPriceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Stock_Management_Service.CA1.internal_static_service1_TotalPrice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Stock_Management_Service.CA1.internal_static_service1_TotalPrice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Stock_Management_Service.TotalPrice.class, Stock_Management_Service.TotalPrice.Builder.class);
    }

    // Construct using Stock_Management_Service.TotalPrice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      quantityOfItems_ = 0;

      totalPrice_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Stock_Management_Service.CA1.internal_static_service1_TotalPrice_descriptor;
    }

    @java.lang.Override
    public Stock_Management_Service.TotalPrice getDefaultInstanceForType() {
      return Stock_Management_Service.TotalPrice.getDefaultInstance();
    }

    @java.lang.Override
    public Stock_Management_Service.TotalPrice build() {
      Stock_Management_Service.TotalPrice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Stock_Management_Service.TotalPrice buildPartial() {
      Stock_Management_Service.TotalPrice result = new Stock_Management_Service.TotalPrice(this);
      result.quantityOfItems_ = quantityOfItems_;
      result.totalPrice_ = totalPrice_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Stock_Management_Service.TotalPrice) {
        return mergeFrom((Stock_Management_Service.TotalPrice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Stock_Management_Service.TotalPrice other) {
      if (other == Stock_Management_Service.TotalPrice.getDefaultInstance()) return this;
      if (other.getQuantityOfItems() != 0) {
        setQuantityOfItems(other.getQuantityOfItems());
      }
      if (other.getTotalPrice() != 0D) {
        setTotalPrice(other.getTotalPrice());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Stock_Management_Service.TotalPrice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Stock_Management_Service.TotalPrice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int quantityOfItems_ ;
    /**
     * <code>int32 quantity_of_items = 1;</code>
     */
    public int getQuantityOfItems() {
      return quantityOfItems_;
    }
    /**
     * <code>int32 quantity_of_items = 1;</code>
     */
    public Builder setQuantityOfItems(int value) {
      
      quantityOfItems_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity_of_items = 1;</code>
     */
    public Builder clearQuantityOfItems() {
      
      quantityOfItems_ = 0;
      onChanged();
      return this;
    }

    private double totalPrice_ ;
    /**
     * <code>double totalPrice = 2;</code>
     */
    public double getTotalPrice() {
      return totalPrice_;
    }
    /**
     * <code>double totalPrice = 2;</code>
     */
    public Builder setTotalPrice(double value) {
      
      totalPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double totalPrice = 2;</code>
     */
    public Builder clearTotalPrice() {
      
      totalPrice_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.TotalPrice)
  }

  // @@protoc_insertion_point(class_scope:service1.TotalPrice)
  private static final Stock_Management_Service.TotalPrice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Stock_Management_Service.TotalPrice();
  }

  public static Stock_Management_Service.TotalPrice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TotalPrice>
      PARSER = new com.google.protobuf.AbstractParser<TotalPrice>() {
    @java.lang.Override
    public TotalPrice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TotalPrice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TotalPrice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TotalPrice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Stock_Management_Service.TotalPrice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

