// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMgmt.proto

package Stock_Management_Service;

public interface TotalPriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TotalPrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 quantity_of_items = 1;</code>
   */
  int getQuantityOfItems();

  /**
   * <code>double totalPrice = 2;</code>
   */
  double getTotalPrice();
}
