/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.client;

import Generated_NumberOfCustomer_Service.CurrentCustomer;
import Generated_NumberOfCustomer_Service.Location;
import Generated_NumberOfCustomer_Service.NumberOfCustomerGrpc;
import Generated_Stock_Management_Service.ItemName;
import Generated_Stock_Monitor_Service.ItemStatus;
import Generated_Stock_Management_Service.StockMgmtGrpc;
import static Generated_Stock_Management_Service.StockMgmtGrpc.newBlockingStub;
import static Generated_Stock_Management_Service.StockMgmtGrpc.newStub;
import Generated_Stock_Management_Service.TotalPrice;
import Generated_Stock_Monitor_Service.Empty;
import Generated_Stock_Monitor_Service.SoldItem;
import Generated_Stock_Monitor_Service.StockMonitorGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;
import java.util.logging.Level;

/**
 *
 * @author User
 */
public class GUIDemo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIDemo.class.getName());
    private static StockMgmtGrpc.StockMgmtBlockingStub blockingStub; // for StockMgmtService
    private static StockMgmtGrpc.StockMgmtStub non_blockingStub; // for StockMgmtService
    private static StockMonitorGrpc.StockMonitorStub stockMonitorNon_blockingStub; // for stockMonitorService
    private static NumberOfCustomerGrpc.NumberOfCustomerStub NumOfCustomerStub;
    private StreamObserver<ItemName> itemName;
    private StreamObserver<TotalPrice> totalPrice;
    private StreamObserver<SoldItem> soldItem;
    private StreamObserver<ItemStatus> itemStatus;
    private StreamObserver<CurrentCustomer> responseCustomer;
    private StreamObserver<Location> locationRequest;

    /**
     * Creates new form GUIDemo
     */
    public GUIDemo() {
        initComponents(); // Initiate the compnents in GUI pannel
        try {
            startService();
        } catch (InterruptedException e) {
            InformationTextArea.setText("Impossible to discovery service");
            logger.log(Level.SEVERE, "Service discovery interrupted ");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StockMonitoringLabel = new javax.swing.JLabel();
        CustomerMonitoringLabel = new javax.swing.JLabel();
        ProductNameLabel = new javax.swing.JLabel();
        ProductStatusLabel = new javax.swing.JLabel();
        ProductsInTheCardLabel = new javax.swing.JLabel();
        TotalPriceLabel = new javax.swing.JLabel();
        ProductNameTextField = new javax.swing.JTextField();
        ProductCheckButton = new javax.swing.JButton();
        StackProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductStatusTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TotalPriceTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        InformationTextArea = new javax.swing.JTextArea();
        InformationLabel = new javax.swing.JLabel();
        NumOfProductLabel = new javax.swing.JLabel();
        NumOfProductTextField = new javax.swing.JTextField();
        CheckPriceButton = new javax.swing.JButton();
        SoldItemLabel = new javax.swing.JLabel();
        SoldButton = new javax.swing.JButton();
        StatusOfSoldItemLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        StatusOfSoldItemTextArea = new javax.swing.JTextArea();
        ProductsInTheCartTextField = new javax.swing.JTextField();
        SoldItemTextField = new javax.swing.JTextField();
        ExpiredItemCheckButton = new javax.swing.JButton();
        ExpiredItemLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ExpiredItemTextArea = new javax.swing.JTextArea();
        CurrentNumCutomerLabel = new javax.swing.JLabel();
        CheckButton = new javax.swing.JButton();
        LocationTextField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        CurrentNumCustomerTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Stock Management Service");

        StockMonitoringLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StockMonitoringLabel.setText("Stock Monitoring Service");

        CustomerMonitoringLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CustomerMonitoringLabel.setText("Customer Monitoring Service");

        ProductNameLabel.setText("Product Name");

        ProductStatusLabel.setText("Product Status");

        ProductsInTheCardLabel.setText("Products in the cart");

        TotalPriceLabel.setText("Total Price");

        ProductCheckButton.setText("Product Check");
        ProductCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductCheckButtonActionPerformed(evt);
            }
        });

        StackProductButton.setText("Stack product");
        StackProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StackProductButtonActionPerformed(evt);
            }
        });

        ProductStatusTextArea.setColumns(20);
        ProductStatusTextArea.setRows(5);
        jScrollPane1.setViewportView(ProductStatusTextArea);

        TotalPriceTextArea.setColumns(20);
        TotalPriceTextArea.setRows(5);
        jScrollPane2.setViewportView(TotalPriceTextArea);

        InformationTextArea.setColumns(20);
        InformationTextArea.setRows(5);
        jScrollPane3.setViewportView(InformationTextArea);

        InformationLabel.setText("Information");

        NumOfProductLabel.setText("Number of product");

        CheckPriceButton.setText("Check price");
        CheckPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPriceButtonActionPerformed(evt);
            }
        });

        SoldItemLabel.setText("Sold Item");

        SoldButton.setText("Sold");
        SoldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldButtonActionPerformed(evt);
            }
        });

        StatusOfSoldItemLabel.setText("Current Stock Status");

        StatusOfSoldItemTextArea.setColumns(20);
        StatusOfSoldItemTextArea.setRows(5);
        jScrollPane4.setViewportView(StatusOfSoldItemTextArea);

        ExpiredItemCheckButton.setText("Check");
        ExpiredItemCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpiredItemCheckButtonActionPerformed(evt);
            }
        });

        ExpiredItemLabel.setText("Expired Item");

        ExpiredItemTextArea.setColumns(20);
        ExpiredItemTextArea.setRows(5);
        jScrollPane5.setViewportView(ExpiredItemTextArea);

        CurrentNumCutomerLabel.setText("Current Number Of Customers");

        CheckButton.setText("check");
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });

        CurrentNumCustomerTextArea.setColumns(20);
        CurrentNumCustomerTextArea.setRows(5);
        jScrollPane6.setViewportView(CurrentNumCustomerTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StockMonitoringLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InformationLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ProductNameLabel)
                                            .addComponent(jLabel1))
                                        .addGap(53, 53, 53)
                                        .addComponent(ProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ProductsInTheCardLabel)
                                        .addGap(27, 27, 27)
                                        .addComponent(ProductsInTheCartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SoldItemLabel)
                                    .addComponent(ExpiredItemLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExpiredItemCheckButton)
                                    .addComponent(SoldItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CustomerMonitoringLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(CurrentNumCutomerLabel)
                                .addGap(27, 27, 27)
                                .addComponent(LocationTextField)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckButton)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProductCheckButton)
                                    .addComponent(StackProductButton)
                                    .addComponent(CheckPriceButton)
                                    .addComponent(SoldButton))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(TotalPriceLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(NumOfProductLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NumOfProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(ProductStatusLabel)
                                            .addGap(65, 65, 65)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(StatusOfSoldItemLabel)
                                        .addGap(35, 35, 35)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductNameLabel)
                            .addComponent(ProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductCheckButton)
                            .addComponent(ProductStatusLabel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductsInTheCardLabel)
                            .addComponent(ProductsInTheCartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StackProductButton)
                            .addComponent(NumOfProductLabel)
                            .addComponent(NumOfProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheckPriceButton)
                        .addComponent(TotalPriceLabel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(StockMonitoringLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SoldItemLabel)
                        .addComponent(SoldItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SoldButton)
                        .addComponent(StatusOfSoldItemLabel))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ExpiredItemCheckButton)
                            .addComponent(ExpiredItemLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(CustomerMonitoringLabel)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentNumCutomerLabel)
                            .addComponent(LocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(CheckButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(InformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductCheckButtonActionPerformed
        if (blockingStub == null) {
            InformationTextArea.setText("Not connected to server");
            return;
        }

        String itemName = ProductNameTextField.getText().trim();

        if (itemName.isEmpty()) {
            ProductStatusTextArea.setText("Please enter a product name");
            return;
        }

        try {
            ItemName request = ItemName.newBuilder().setItemName(itemName).build();
            Generated_Stock_Management_Service.ItemStatus status = blockingStub.stockCheck(request);
            ProductStatusTextArea.setText(status.toString());
        } catch (Exception e) {
            InformationTextArea.setText("Error occured while executing stockChek service");
            logger.log(Level.SEVERE, "Error occured while executing stockChek service");
        }

    }//GEN-LAST:event_ProductCheckButtonActionPerformed

    private void StackProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StackProductButtonActionPerformed
        if (itemName == null) {
            InformationTextArea.setText("Streaming service is not connected");
            return;
        }

        String productName = ProductsInTheCartTextField.getText().trim();

        if (productName.isEmpty()) {
            InformationTextArea.setText("Please enter a product name");
            return;
        }

        try {
            ItemName newItem = ItemName.newBuilder().setItemName(productName).build();
            itemName.onNext(newItem);

        } catch (Exception e) {
            InformationTextArea.setText("Error while stacking product");
            logger.log(Level.SEVERE, "Error while stacking product", e);
        } finally {
            ProductsInTheCartTextField.setText("");
        }

    }//GEN-LAST:event_StackProductButtonActionPerformed

    private void CheckPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPriceButtonActionPerformed
        if (itemName == null) {
            InformationTextArea.setText("No product is added");
            return;
        }
        try {
            itemName.onCompleted();

            InformationTextArea.setText("Total price calculation completed");
        } catch (Exception e) {
            InformationTextArea.setText("Error occured in CheckPriceButtonActionPerformed()");
            logger.log(Level.SEVERE, "Error occured in CheckPriceButtonActionPerformed()", e);
        } finally {
            itemName = non_blockingStub.basketPrice(totalPrice);
        }

    }//GEN-LAST:event_CheckPriceButtonActionPerformed

    private void SoldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldButtonActionPerformed
        if (soldItem == null) {
            // if it is null, that means the connection with server isn't generated
            return;
        }

        String soldItemName = SoldItemTextField.getText().trim();

        if (soldItemName.isEmpty()) {
            return;
        }

        try {
            SoldItem request = SoldItem.newBuilder()
                    .setItemName(soldItemName)
                    .build();

            soldItem.onNext(request);
            // it will activate autoStockCheck() method in server
            // it sends a request which has one field(item_name) to server when the button is clicked
            // After this, the server's reply will be sent to itemStatus

            InformationTextArea.setText("Sold item request sent: " + soldItemName);

        } catch (Exception e) {
            InformationTextArea.setText("Error while sending sold item request");
            logger.log(Level.SEVERE, "Error while sending sold item request", e);
        } finally {
            SoldItemTextField.setText("");
        }


    }//GEN-LAST:event_SoldButtonActionPerformed

    private void ExpiredItemCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpiredItemCheckButtonActionPerformed
        ExpiredItemTextArea.setText(" ");
        Empty request = Empty.newBuilder().build();
        StreamObserver<ItemStatus> response = new StreamObserver<ItemStatus>() {
            public void onNext(ItemStatus status) {
                ExpiredItemTextArea.append(status.toString() + "\n\n");

            }

            public void onError(Throwable t) {
                logger.log(Level.SEVERE, "Issue occurs in ExpiredItemCheckButton()", t);
                InformationTextArea.setText("Issue occurs in ExpiredItemCheckButton()");

            }

            public void onCompleted() {
                InformationTextArea.setText("Expired item check completed");

            }
        };
        stockMonitorNon_blockingStub.expiryDate(request, response);


    }//GEN-LAST:event_ExpiredItemCheckButtonActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
        if (locationRequest == null) {
            return;
        }
        String place = LocationTextField.getText().trim();
        
        if(place.isEmpty()){
            return;
        }

        try {
            Location request = Location.newBuilder()
                                .setLocation(place)
                                .build();
            
            locationRequest.onNext(request);
        }
        catch(Exception e){
            logger.log(Level.SEVERE, "Error occurs at CheckButtonActionPerformed()", e);
            InformationTextArea.setText("Error occurs at CheckButtonActionPerformed()");
            
        }
    }//GEN-LAST:event_CheckButtonActionPerformed

    private void startService() throws InterruptedException {
        int port;
        String host;
        ServiceDiscovery discovery = new ServiceDiscovery("_grpc._tcp.local.", "Server main");
        // Looking up the service name. All the services are registered by one name(Server main)
        discovery.discoverService(5000);

        port = discovery.getPort();
        host = discovery.getHost();

        if (host == null || port == 0) {
            InformationTextArea.setText("Service is not found");
            return;
        }

        ManagedChannel channel = ManagedChannelBuilder
                .forAddress(host, port)
                .usePlaintext()
                .build();

        blockingStub = newBlockingStub(channel); // for StockMgmtService
        non_blockingStub = newStub(channel); // for StockMgmtService
        stockMonitorNon_blockingStub = StockMonitorGrpc.newStub(channel); // for StockMonitorService
        NumOfCustomerStub = Generated_NumberOfCustomer_Service.NumberOfCustomerGrpc.newStub(channel);

        /* For client streaming method: basckePrice()*/
        totalPrice = new StreamObserver<TotalPrice>() {

            public void onNext(TotalPrice p) {
                // It is executed only once when the CheckPriceButtonActionPerformed()is activated
                TotalPriceTextArea.setText(String.valueOf(p.getTotalPrice()));
                NumOfProductTextField.setText(String.valueOf(p.getQuantityOfItems()));

            }

            public void onError(Throwable t) {
                logger.log(Level.SEVERE, "Issue occurs in basketPrkce()", t);
                InformationTextArea.setText("Issue occurs basketPrkce()");
            }

            public void onCompleted() {

                InformationTextArea.setText("Price calculation completed");

            }
        };
        itemName = non_blockingStub.basketPrice(totalPrice);
        /*-------------------------------------------------*/

 /*For bidirectional streaming: autoStockCheck() and SoldButtonActionPerformed()*/
        // create StreamObserver (path for receiving answer from server)
        itemStatus = new StreamObserver<ItemStatus>() {

            public void onNext(ItemStatus item) {
                StatusOfSoldItemTextArea.setText(item.toString());
            } // It will be executed when the server send reply

            public void onError(Throwable t) {
                logger.log(Level.SEVERE, "Issue occurs in autoStockCheck()", t);
                InformationTextArea.setText("Issue occurs autoStockCheck()");

            }

            public void onCompleted() {
                InformationTextArea.setText("Stock status is updated");
            }
        };

        soldItem = stockMonitorNon_blockingStub.autoStockCheck(itemStatus);
        // Connect with server
        // the argument(itemStatus) configures the path that the reply comes through
        // the return value is StreamObserver<ItemaName> type that same as 'soldItem'
        /*-------------------------------------------------*/

 /*For bidirectional streaming: checkNumOfCustomer() and CheckButtonActionPerformed()*/
        responseCustomer = new StreamObserver<CurrentCustomer>() {
            public void onNext(CurrentCustomer c) {
                CurrentNumCustomerTextArea.setText("Section: " + c.getLocation() + "\n\nCurrent customer: " + c.getCurrentNum());
            }

            public void onError(Throwable t) {
                logger.log(Level.SEVERE, "Error occurs at CheckButtonActionPerformed()");
                InformationTextArea.setText("Error occurs at CheckButtonActionPerformed()");
            }

            public void onCompleted() {
                InformationTextArea.setText("Current number of customers updated");
            }

        };
        locationRequest = NumOfCustomerStub.checkNumOfCustomer(responseCustomer);

        InformationTextArea.setText("Connected\nHost: " + host + "\nPort: " + port);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIDemo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckButton;
    private javax.swing.JButton CheckPriceButton;
    private javax.swing.JTextArea CurrentNumCustomerTextArea;
    private javax.swing.JLabel CurrentNumCutomerLabel;
    private javax.swing.JLabel CustomerMonitoringLabel;
    private javax.swing.JButton ExpiredItemCheckButton;
    private javax.swing.JLabel ExpiredItemLabel;
    private javax.swing.JTextArea ExpiredItemTextArea;
    private javax.swing.JLabel InformationLabel;
    private javax.swing.JTextArea InformationTextArea;
    private javax.swing.JTextField LocationTextField;
    private javax.swing.JLabel NumOfProductLabel;
    private javax.swing.JTextField NumOfProductTextField;
    private javax.swing.JButton ProductCheckButton;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTextField;
    private javax.swing.JLabel ProductStatusLabel;
    private javax.swing.JTextArea ProductStatusTextArea;
    private javax.swing.JLabel ProductsInTheCardLabel;
    private javax.swing.JTextField ProductsInTheCartTextField;
    private javax.swing.JButton SoldButton;
    private javax.swing.JLabel SoldItemLabel;
    private javax.swing.JTextField SoldItemTextField;
    private javax.swing.JButton StackProductButton;
    private javax.swing.JLabel StatusOfSoldItemLabel;
    private javax.swing.JTextArea StatusOfSoldItemTextArea;
    private javax.swing.JLabel StockMonitoringLabel;
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JTextArea TotalPriceTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
