/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.client;

import Generated_Stock_Management_Service.ItemName;
import Generated_Stock_Management_Service.ItemStatus;
import Generated_Stock_Management_Service.StockMgmtGrpc;
import static Generated_Stock_Management_Service.StockMgmtGrpc.newBlockingStub;
import static Generated_Stock_Management_Service.StockMgmtGrpc.newStub;
import Generated_Stock_Management_Service.TotalPrice;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;
import java.util.logging.Level;

/**
 *
 * @author User
 */
public class GUIDemo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIDemo.class.getName());
    private static StockMgmtGrpc.StockMgmtBlockingStub blockingStub;
    private static StockMgmtGrpc.StockMgmtStub non_blockingStub;
    private StreamObserver<ItemName> itemName;
    private StreamObserver<TotalPrice> totalPrice;

    /**
     * Creates new form GUIDemo
     */
    public GUIDemo() {
        initComponents(); // Initiate the compnents in GUI pannel
        try {
            startService();
        } catch (InterruptedException e) {
            InformationTextArea.setText("Impossible to discovery service");
            logger.log(Level.SEVERE, "Service discovery interrupted ");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StockMonitoringLabel = new javax.swing.JLabel();
        CustomerMonitoringLabel = new javax.swing.JLabel();
        ProductNameLabel = new javax.swing.JLabel();
        ProductStatusLabel = new javax.swing.JLabel();
        ProductsInTheCardLabel = new javax.swing.JLabel();
        TotalPriceLabel = new javax.swing.JLabel();
        ProductNameTextField = new javax.swing.JTextField();
        ProductsInTheCartTextField = new javax.swing.JTextField();
        ProductCheckButton = new javax.swing.JButton();
        StackProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductStatusTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TotalPriceTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        InformationTextArea = new javax.swing.JTextArea();
        InformationLabel = new javax.swing.JLabel();
        NumOfProductLabel = new javax.swing.JLabel();
        NumOfProductTextField = new javax.swing.JTextField();
        CheckPriceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Stock Management");

        StockMonitoringLabel.setText("Stock Monitoring");

        CustomerMonitoringLabel.setText("Customer Monitoring");

        ProductNameLabel.setText("Product Name");

        ProductStatusLabel.setText("Product Status");

        ProductsInTheCardLabel.setText("Products in the cart");

        TotalPriceLabel.setText("Total Price");

        ProductsInTheCartTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsInTheCartTextFieldActionPerformed(evt);
            }
        });

        ProductCheckButton.setText("Product Check");
        ProductCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductCheckButtonActionPerformed(evt);
            }
        });

        StackProductButton.setText("Stack product");
        StackProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StackProductButtonActionPerformed(evt);
            }
        });

        ProductStatusTextArea.setColumns(20);
        ProductStatusTextArea.setRows(5);
        jScrollPane1.setViewportView(ProductStatusTextArea);

        TotalPriceTextArea.setColumns(20);
        TotalPriceTextArea.setRows(5);
        jScrollPane2.setViewportView(TotalPriceTextArea);

        InformationTextArea.setColumns(20);
        InformationTextArea.setRows(5);
        jScrollPane3.setViewportView(InformationTextArea);

        InformationLabel.setText("Information");

        NumOfProductLabel.setText("Number of product");

        CheckPriceButton.setText("Check price");
        CheckPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPriceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProductNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductCheckButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ProductsInTheCardLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductsInTheCartTextField)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckPriceButton)
                            .addComponent(StackProductButton))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ProductStatusLabel)
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumOfProductLabel)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(NumOfProductTextField))))
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StockMonitoringLabel))
                    .addComponent(CustomerMonitoringLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InformationLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(TotalPriceLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductStatusLabel)
                            .addComponent(ProductCheckButton)
                            .addComponent(ProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductNameLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(TotalPriceLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StackProductButton)
                                    .addComponent(ProductsInTheCartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductsInTheCardLabel)
                                    .addComponent(NumOfProductLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckPriceButton)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(NumOfProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addComponent(StockMonitoringLabel)
                .addGap(234, 234, 234)
                .addComponent(CustomerMonitoringLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(InformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductsInTheCartTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsInTheCartTextFieldActionPerformed
        // nothing


    }//GEN-LAST:event_ProductsInTheCartTextFieldActionPerformed

    private void ProductCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductCheckButtonActionPerformed
        if (blockingStub == null) {
            InformationTextArea.setText("Not connected to server");
            return;
        }

        String itemName = ProductNameTextField.getText().trim();

        if (itemName.isEmpty()) {
            ProductStatusTextArea.setText("Please enter a product name");
            return;
        }

        try {
            ItemName request = ItemName.newBuilder().setItemName(itemName).build();
            ItemStatus itemStatus = blockingStub.stockCheck(request);
            ProductStatusTextArea.setText(itemStatus.toString());
        } catch (Exception e) {
            InformationTextArea.setText("Error occured while executing stockChek service");
            logger.log(Level.SEVERE, "Error occured while executing stockChek service");
        }

    }//GEN-LAST:event_ProductCheckButtonActionPerformed

    private void StackProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StackProductButtonActionPerformed
        if (itemName == null) {
            InformationTextArea.setText("Streaming service is not connected");
            return;
        }

        String productName = ProductsInTheCartTextField.getText().trim();

        if (productName.isEmpty()) {
            InformationTextArea.setText("Please enter a product name");
            return;
        }

        try {
            itemName.onNext(ItemName.newBuilder().setItemName(productName).build());
            

        } catch (Exception e) {
            InformationTextArea.setText("Error while stacking product");
            logger.log(Level.SEVERE, "Error while stacking product", e);
        } finally {
            ProductsInTheCartTextField.setText("");
        }

    }//GEN-LAST:event_StackProductButtonActionPerformed

    private void CheckPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPriceButtonActionPerformed
        if (itemName == null) {
            InformationTextArea.setText("No product is added");
            return;
        }
        try {
            itemName.onCompleted();
            
            InformationTextArea.setText("Total price calculation completed");
        } catch (Exception e) {
            InformationTextArea.setText("Error occured in CheckPriceButtonActionPerformed()");
            logger.log(Level.SEVERE, "Error occured in CheckPriceButtonActionPerformed()", e);
        } finally {
            itemName = non_blockingStub.basketPrice(totalPrice);
        }

    }//GEN-LAST:event_CheckPriceButtonActionPerformed

    private void startService() throws InterruptedException {
        int port;
        String host;
        ServiceDiscovery discovery = new ServiceDiscovery("_grpc._tcp.local.", "Stock management"); // Looking up the service by discovery object
        discovery.discoverService(5000);

        port = discovery.getPort();
        host = discovery.getHost();

        if (host == null || port == 0) {
            InformationTextArea.setText("Service is not found");
            return;
        }

        ManagedChannel channel = ManagedChannelBuilder
                .forAddress(host, port)
                .usePlaintext()
                .build();

        blockingStub = newBlockingStub(channel);
        non_blockingStub = newStub(channel);

        totalPrice = new StreamObserver<TotalPrice>() {

            public void onNext(TotalPrice p) {
                TotalPriceTextArea.setText(String.valueOf(p.getTotalPrice()));
                NumOfProductTextField.setText(String.valueOf(p.getQuantityOfItems()));

            }

            public void onError(Throwable t) {
                logger.log(Level.SEVERE, "Issue occurs in getTotalBasketPrkce()", t);
                InformationTextArea.setText("Issue occurs in getTotalBasketPrkce()");
            }

            public void onCompleted() {

                InformationTextArea.setText("Price calculation completed");

            }
        };
        itemName = non_blockingStub.basketPrice(totalPrice);

        InformationTextArea.setText("Connected\nHost: " + host + "\nPort: " + port);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIDemo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckPriceButton;
    private javax.swing.JLabel CustomerMonitoringLabel;
    private javax.swing.JLabel InformationLabel;
    private javax.swing.JTextArea InformationTextArea;
    private javax.swing.JLabel NumOfProductLabel;
    private javax.swing.JTextField NumOfProductTextField;
    private javax.swing.JButton ProductCheckButton;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTextField;
    private javax.swing.JLabel ProductStatusLabel;
    private javax.swing.JTextArea ProductStatusTextArea;
    private javax.swing.JLabel ProductsInTheCardLabel;
    private javax.swing.JTextField ProductsInTheCartTextField;
    private javax.swing.JButton StackProductButton;
    private javax.swing.JLabel StockMonitoringLabel;
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JTextArea TotalPriceTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
