// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMgmt.proto

package Generated_Stock_Management_Service;

public final class CA1 {
  private CA1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_ItemName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_ItemName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Items_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Items_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_ItemStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_ItemStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TotalPrice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TotalPrice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017StockMgmt.proto\022\010service1\"\035\n\010ItemName\022" +
      "\021\n\titem_name\030\001 \001(\t\")\n\005Items\022\021\n\titem_name" +
      "\030\001 \001(\t\022\r\n\005price\030\002 \001(\001\"X\n\nItemStatus\022\021\n\ti" +
      "tem_name\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\022\023\n\013expi" +
      "ry_date\030\003 \001(\t\022\020\n\010location\030\004 \001(\t\";\n\nTotal" +
      "Price\022\031\n\021quantity_of_items\030\001 \001(\005\022\022\n\ntota" +
      "lPrice\030\002 \001(\0012\177\n\tStockMgmt\0228\n\nStockCheck\022" +
      "\022.service1.ItemName\032\024.service1.ItemStatu" +
      "s\"\000\0228\n\013BasketPrice\022\017.service1.Items\032\024.se" +
      "rvice1.TotalPrice\"\000(\001B+\n\"Generated_Stock" +
      "_Management_ServiceB\003CA1P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_ItemName_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_ItemName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_ItemName_descriptor,
        new java.lang.String[] { "ItemName", });
    internal_static_service1_Items_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_Items_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Items_descriptor,
        new java.lang.String[] { "ItemName", "Price", });
    internal_static_service1_ItemStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_ItemStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_ItemStatus_descriptor,
        new java.lang.String[] { "ItemName", "Quantity", "ExpiryDate", "Location", });
    internal_static_service1_TotalPrice_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_TotalPrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TotalPrice_descriptor,
        new java.lang.String[] { "QuantityOfItems", "TotalPrice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
