// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMgmt.proto

package Generated_Stock_Management_Service;

public interface ItemStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ItemStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item_name = 1;</code>
   */
  java.lang.String getItemName();
  /**
   * <code>string item_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemNameBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();

  /**
   * <code>string expiry_date = 3;</code>
   */
  java.lang.String getExpiryDate();
  /**
   * <code>string expiry_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getExpiryDateBytes();

  /**
   * <code>string location = 4;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 4;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
