// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMgmt.proto

package Generated_Stock_Management_Service;

public interface ItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Items)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item_name = 1;</code>
   */
  java.lang.String getItemName();
  /**
   * <code>string item_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemNameBytes();

  /**
   * <code>double price = 2;</code>
   */
  double getPrice();
}
