// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMonitor.proto

package Generated_Stock_Monitor_Service;

public final class CA1 {
  private CA1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_ItemStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_ItemStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_SoldItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_SoldItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StockMonitor.proto\022\010service2\"\007\n\005Empty\"" +
      "X\n\nItemStatus\022\021\n\titem_name\030\001 \001(\t\022\020\n\010quan" +
      "tity\030\002 \001(\005\022\023\n\013expiry_date\030\003 \001(\t\022\020\n\010locat" +
      "ion\030\004 \001(\t\"\035\n\010SoldItem\022\021\n\titem_name\030\001 \001(\t" +
      "2\211\001\n\014StockMonitor\0227\n\nExpiryDate\022\017.servic" +
      "e2.Empty\032\024.service2.ItemStatus\"\0000\001\022@\n\016Au" +
      "toStockCheck\022\022.service2.SoldItem\032\024.servi" +
      "ce2.ItemStatus\"\000(\0010\001B(\n\037Generated_Stock_" +
      "Monitor_ServiceB\003CA1P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_service2_ItemStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_ItemStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_ItemStatus_descriptor,
        new java.lang.String[] { "ItemName", "Quantity", "ExpiryDate", "Location", });
    internal_static_service2_SoldItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_SoldItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_SoldItem_descriptor,
        new java.lang.String[] { "ItemName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
