// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMonitor.proto

package Generated_Stock_Monitor_Service;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.Empty)
    com.google.protobuf.MessageOrBuilder {
}
