// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMonitor.proto

package Generated_Stock_Monitor_Service;

public interface SoldItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.SoldItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item_name = 1;</code>
   */
  java.lang.String getItemName();
  /**
   * <code>string item_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemNameBytes();
}
